### ISSUE TITLE
Remove some dockerfiles

### ISSUE THREAD

**Issue by nudles** [nusdbsystem/singa-auto#111]
1. Currently, we have many [dockerfiles](https://github.com/nusdbsystem/singa-auto/tree/dev/dockerfiles). Most of them are doing trivial tasks like installing conda, copying files and then pip install...
Instead of maintaining these dockerfiles and the corresponding images, we can run the commands when launching the docker container. 

For example, the [admin dockerfile](https://github.com/nusdbsystem/singa-auto/blob/dev/dockerfiles/admin.Dockerfile) can be removed by

```bash
docker run -p port:3000 continuumio/miniconda  git clone https://github.com/nusdbsystem/singa-auto.git \
      && git checkout dev && pip install singa-auto && pip install singa-auto admin/requirements.txt
```

In this way, we do not need to build and maintain the docker images.

2.  for worker.dockerfile, we do not need to install cudnn manually. there are [docker images](https://hub.docker.com/r/nvidia/cuda/tags?page=1&name=cudnn) provided by nvidia which already have cudnn.

3. torchtest.dockerfile has nothing to do with torch.

4. when and how to use spark.dockerfile?

@naili-xing  can you reply to this issue about which dockerfile cannot be reduced and why?

**Comment by naili-xing** [comment]
0. we can remove the elasticsearch.Dockerfile, spark.Dockerfile, or logstash.Dockerfile. and attache the necessary configure file when running the container. 
1. In worker docker file (currently we use nvidia/cuda:9.0-base-ubuntu16.04 ), We had to find right version compatible with our panda node1,2,3 and re-test gpu usage etc.
2. we can remove torchtest.Dockerfile and test.Dockerfile which are used to test the container runtime. 
3. spark.dockerfile is used to launch the spark-streaming job, 
4. The reason why we have many requirements is that we don't want each docker container install some unnecessary dependences. eg: predictor container doesn't need torch or tf dependence. 

ps: Building image is convenient at this stage, i never meet any error in building process. I would suggest in production, we change the "copy" to "git clone" inside the docker files. And in dev, we still use copy, as it's easy to debug. But we can keep the admin, worker, predictor, web docker files. 

Removing the docker files is a super big change, All configuration files (generated by create_config.py ) in k8s are needed to change, and all docker scripts are needed to change also.  All test need to do again.

**Comment by nudles** [comment]
> 
> 
>     1. we can remove the elasticsearch.Dockerfile, spark.Dockerfile, or logstash.Dockerfile. and attache the necessary configure file when running the container.
> 
>     2. In worker docker file (currently we use nvidia/cuda:9.0-base-ubuntu16.04 ), We had to find right version compatible with our panda node1,2,3 and re-test gpu usage etc.

then just find the docker image with the correct cuda and cudnn version from nvidia's docker hub.

> 
>     3. we can remove torchtest.Dockerfile and test.Dockerfile which are used to test the container runtime.
> 
>     4. spark.dockerfile is used to launch the spark-streaming job,

I think we do not need to support spark jobs.

> 
>     5. The reason why we have many requirements is that we don't want each docker container install some unnecessary dependences. eg: predictor container doesn't need torch or tf dependence.

then just prepare a requirements.txt for each container instead of having multiple requirements.txt for each container.
> 
> 
> ps: Building image is convenient at this stage, i never meet any error in building process. I would suggest in production, we change the "copy" to "git clone" inside the docker files. And in dev, we still use copy, as it's easy to debug. But we can keep the admin, worker, predictor, web docker files.

If I am going to deploy singa-auto, do I need to build the images first? can I just do some simple configurations (for the cluster information) and then run pip install to install/deploy it? that is the easiest way.
> 
> Removing the docker files is a super big change, All configuration files (generated by create_config.py ) in k8s are needed to change, and all docker scripts are needed to change also. All test need to do again.

what's the relationship between dockerfiles and config files? why will there be a big change?

**Comment by naili-xing** [comment]
1. If u are going to deploy singa-auto,  u don't need to build urself, u only need to git clone & bash start.sh, that's all.  The start.sh will pull the image from https://hub.docker.com/repository/docker/singaauto/singa_auto_admin

2. For k8s, if we launch a service, we need the service related configuration file.  which is generate by running create_config.py. 
 Create_config.py. will generate config file using the current docker file, If we remove them, we had to move the commend (in docker file previously) to  create_config.py, 
    For docker swarm,  all docker run commends are needed to rewrite. 

I suggest we set 2 deployment methods, one for user, one for developer. I will think about this later.  User don't need to change the code. so we can package everything, Developer needs to update the code, packaging whole thing is hard to debug.

**Comment by naili-xing** [comment]
Now i think this is not a good idea, i have tried with following:
in start.sh
```sh
docker run --rm \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v $HOST_WORKDIR_PATH/scripts:/scripts \
  --name sa_admin ubuntu:16.04 /bin/sh ./scripts/docker_swarm/start_admin.sh \
  -e POSTGRES_HOST=$POSTGRES_HOST \
  -e POSTGRES_PORT=$POSTGRES_PORT \
  -e POSTGRES_USER=$POSTGRES_USER \
  -e POSTGRES_DB=$POSTGRES_DB \
  -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
  -e SUPERADMIN_PASSWORD=$SUPERADMIN_PASSWORD \
  -e ADMIN_HOST=$ADMIN_HOST \
  -e ADMIN_PORT=$ADMIN_PORT \
  -e REDIS_HOST=$REDIS_HOST \
  -e REDIS_PORT=$REDIS_PORT \
  -e REDIS_PASSWORD=$REDIS_PASSWORD \
  -e KAFKA_HOST=$KAFKA_HOST \
  -e KAFKA_PORT=$KAFKA_PORT \
  -e PREDICTOR_PORT=$PREDICTOR_PORT \
  -e SINGA_AUTO_ADDR=$SINGA_AUTO_ADDR \
  -e SINGA_AUTO_IMAGE_WORKER=$SINGA_AUTO_IMAGE_WORKER \
  -e SINGA_AUTO_IMAGE_PREDICTOR=$SINGA_AUTO_IMAGE_PREDICTOR \
  -e SINGA_AUTO_VERSION=$SINGA_AUTO_VERSION \
  -e DOCKER_WORKDIR_PATH=$DOCKER_WORKDIR_PATH \
  -e WORKDIR_PATH=$DOCKER_WORKDIR_PATH \
  -e HOST_WORKDIR_PATH=$HOST_WORKDIR_PATH \
  -e DATA_DIR_PATH=$DATA_DIR_PATH \
  -e PARAMS_DIR_PATH=$PARAMS_DIR_PATH \
  -e LOGS_DIR_PATH=$LOGS_DIR_PATH \
  -e APP_MODE=$APP_MODE \
  -e CONTAINER_MODE=$CONTAINER_MODE \
  -e CONDA_ENVIORNMENT=$CONDA_ENVIORNMENT \
  -p $ADMIN_EXT_PORT:$ADMIN_PORT \
```

And in start_admin.sh:

```sh

apt-get update && apt-get -y upgrade
apt-get -y install curl bzip2 \
  && curl -sSL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh \
  && bash /tmp/miniconda.sh -bfp /usr/local \
  && rm -rf /tmp/miniconda.sh \
  && conda create -y --name $CONDA_ENVIORNMENT python=3.6 \
  && conda clean --all --yes

export PATH=$PATH:/usr/local/envs/$CONDA_ENVIORNMENT/bin
export PYTHONUNBUFFERED=1

pip install --upgrade pip
RUN mkdir -p $DOCKER_WORKDIR_PATH

pip install -r singa_auto/requirements.txt
pip install -r singa_auto/utils/requirements.txt
pip install -r singa_auto/meta_store/requirements.txt
pip install -r singa_auto/container/requirements.txt
pip install -r singa_auto/admin/requirements.txt
git clone --single-branch --branch dev git@github.com:nusdbsystem/singa-auto.git
cd singa-auto
python scripts/start_admin.py

```


which can run successfully, but since we move apt-get & pip install to such a bash scripts. every time we launch the admin service, it needs to run those installation setup. As a result, launch a service is very slow. 

Docker image has those layer built inside to it when we run docker build. so we can start service quickly after pulling the images

**Comment by naili-xing** [comment]
I will simply the docker images,  but let's keep using docker file, which is the most convenient way.
