### ISSUE TITLE
tabular_classification/LogisticRegClf.py 

### ISSUE THREAD

**Issue by delphieritas** [nusdbsystem/singa-auto#127]
bug location:
https://github.com/nusdbsystem/singa-auto/blob/dev/examples/models/tabular_classification/LogisticRegClf.py

err msg:
Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

suggestion:
remove l1 penalty

**Comment by delphieritas** [comment]
pls merge https://github.com/nusdbsystem/singa-auto/compare/dev...delphieritas:patch-2 for bug fixing

**Comment by pinpom** [comment]
@delphieritas: I purposely set the params as a list for tuning, given that singa-auto can automate the hyperparameter tuning process for models, and will pick the best trials for inference job. For example, 'lbfgs' solver does not work with 'l1' penalty, so the tuning process will continue using 'liblinear' solver for 'l1' penalty. So It's not a bug, i think. same reasoning applied for other models.

**Comment by delphieritas** [comment]
> @delphieritas: I purposely set the params as a list for tuning, given that singa-auto can automate the hyperparameter tuning process for models, and will pick the best trials for inference job. For example, 'lbfgs' solver does not work with 'l1' penalty, so the tuning process will continue using 'liblinear' solver for 'l1' penalty. So It's not a bug, i think. same reasoning applied for other models.

Oh, I see. Honestly I haven't managed to test them with Singa-Auto. Only tested them locally, but without the Singa-Auto tuning mechanism, I got errors.

Do you have a stable Singa-Auto for me to upload models and test?
