### ISSUE TITLE
Web UI: Some bugs in graph display

### ISSUE THREAD

**Issue by chrishkchris** [nusdbsystem/singa-auto#136]
When we look at the curve below, there are two errors:

1. When the x data start from 1, the plot should also start at the same point (x=1). This is because the loss at epoch 0 is not 0,  since there is no data it displays 0 (this is highly confusing to user).

2. Y-axis is named "Loss Over Epochs", but actually there are two curves for loss and accuracy. In this case the Y-axis can be renamed as Value instead.

![image](https://user-images.githubusercontent.com/38325429/91532286-ab56e980-e940-11ea-8240-2d9e3411dd1c.png)

**Comment by chrishkchris** [comment]
Also, since loss and accuracy are in a different scale, could consider to separate them in two graphs

**Comment by arielclj** [comment]
@chrishkchris For this example, by having the plot start @ x=1 would mean that the graph presents a data point instead of a line. Is this the refinement you had in mind?

**Comment by chrishkchris** [comment]
in usual case, there are 5-50 epochs so it appears as a line. 
It is not common to train for only 1 epoch. 
I think 1 epoch is only for test purpose
When there is only 1 epoch, I also prefer using a point instead of line (as this is not misleading)

**Comment by arielclj** [comment]
![SS2](https://user-images.githubusercontent.com/12420470/91792537-4ead4480-ec48-11ea-8060-145213dea2e7.png)

For this trial, there is a point 0- epoch: 0, epoch_accuracy: 0, loss: 0.

In this scenario, would you want the point 0 to be plotted?

**Comment by chrishkchris** [comment]
> ![SS2](https://user-images.githubusercontent.com/12420470/91792537-4ead4480-ec48-11ea-8060-145213dea2e7.png)
> 
> For this trial, there is a point 0- epoch: 0, epoch_accuracy: 0, loss: 0.
> 
> In this scenario, would you want the point 0 to be plotted?

No, loss should not be equal to 0 at epoch. This is the exact reason I raised the point 1

**Comment by chrishkchris** [comment]
solved
