### ISSUE TITLE
Package and Installation

### ISSUE THREAD

**Issue by nudles** [nusdbsystem/singa-auto#14]
A single conda package for all rafiki code
```
conda install rafiki
```
It copy the rafiki py files into a system folder  `/home/wangwei/miniconda3/lib/python3.7/site-packages/rafiki`

A docker image with rafiki and the dependent libs/tools installed

When the docker container is launched, run one of the following commands
```
rafiki start admin &
rafiki start worker &  
rafiki start advisor &
```

Make panda a separate lib that depends on rafiki
```
conda install panda
```
It copy the panda py files into a system folder  `/home/wangwei/miniconda3/lib/python3.7/site-packages/panda`

In panda py file, to use rafiki module, we need `import rafiki`

In user's model py file, to use rafiki and panda, we need `import rafiki` and `import panda` respectively

**Comment by chrishkchris** [comment]
@nudles Thanks a lot! 

@naili-xing This one is the plan for conda

**Comment by chrishkchris** [comment]
@naili-xing So recently we can see how to do the synchronization of code as discussed in the email and last meeting between Rafiki and Panda recently (the slide below is for reference)

![Progress Report_30March](https://user-images.githubusercontent.com/38325429/78033924-a4c84400-7399-11ea-983b-dd15954ed93d.jpg)

**Comment by socdbsystem** [comment]
We can use either conda or pip for the package management.
