### ISSUE TITLE
When GPU is available, Please deploy SINGA-auto with GPU enabled for acceleration

### ISSUE THREAD

**Issue by chrishkchris** [nusdbsystem/singa-auto#42]
When GPU is available, Please deploy SINGA-auto with GPU enabled to accelerate training and inference. Otherwise, the training and inference using CPU is very slow.

For example, it is almost impossible to use CPU only to train a very deep network such as Resnet101. Also, it will need the end-user to wait for long time in inference job

To deploy SINGA-auto with GPU enabled, please follow the instruction in this page https://nginyc.github.io/rafiki/docs/latest/src/dev/setup.html#scaling-rafiki

The key is to run the script to enable the GPU 
`bash scripts/setup_node.sh`

@naili-xing  If you encounter any problem when using GPU at inference job, please reply the issue here

**Comment by pinpom** [comment]
i think can use GPU for inference job, you can check ./client/client.py

`def create_inference_job(self, app: str, app_version: int = -1, budget: InferenceBudget = None) -> Dict[str, Any]:
        '''
        Creates and starts a inference job on SINGA-Auto with the best-scoring trials of the associated train job.
        The train job must have the status of ``STOPPED``.The inference job would be tagged with the train job's app and app version.
        Throws an error if an inference job of the same train job is already running.

        In this method's response, `predictor_host` is this inference job's predictor's host.

        Only admins, model developers & app developers can manage inference jobs. Model developers & app developers can only manage their own inference jobs.

        :param app: Name of the app identifying the train job to use
        :param app_version: Version of the app identifying the train job to use
        :param budget: Budget for inference job
        :returns: Created inference job as dictionary

        ``budget`` should be a dictionary of ``{ <budget_type>: <budget_amount> }``, where
        ``<budget_type>`` is one of :class:`singa_auto.constants.InferenceBudgetOption` and
        ``<budget_amount>`` specifies the amount for the associated budget option.

        The following describes the budget options available:

        =====================       =====================
        **Budget Option**             **Description**
        ---------------------       ---------------------
        ``GPU_COUNT``               No. of GPUs to allocate for inference, across all trials. Defaults to 0.
        =====================       =====================
        '''

        # Have defaults for budget
        budget = {
            InferenceBudgetOption.GPU_COUNT: 0,
            **(budget or {})
        }

        data = self._post('/inference_jobs', json={
            'app': app,
            'app_version': app_version,
            'budget': budget
        })
        return data`
