### ISSUE TITLE
Add Model Description and Model Input Param Description for Predict

### ISSUE THREAD

**Issue by airlovelq** [nusdbsystem/singa-auto#56]
This is an issue found in binding sign-auto to forkcloud. if we support a predict service for user, service user need to know the description of model such as model usage, and the format of data using for predict such as vedio, picture, or csv. So we add model description and model input param description column in db table, and edit the related code.

**Comment by nudles** [comment]
https://singa-auto.readthedocs.io/en/latest/src/user/tasks.html?highlight=TASK

**Comment by xuyin224** [comment]
For the parameters we will follow the task parameter design. Just add two optional description fields for the model and inference job.
