### ISSUE TITLE
Configure the service port

### ISSUE THREAD

**Issue by nudles** [nusdbsystem/singa-auto#7]
When we create an inference service, the port is automatically generated. That means the website needs to update the endpoint once we restart the service.
To fix this issue, we can make the port number as one configuration option when we launch the service.

**Comment by naili-xing** [comment]
one good solution is to provide the admin endpoint, web send inference request to admin,  admin will get the predictor service's port and transfer the request to it. However,  the ui will be different between the predictor services.

**Comment by nudles** [comment]
Will all requests go to the admin for redirection?
If so, the admin needs to handle a lot of requests.

**Comment by naili-xing** [comment]
yes, admin will handle a lot requests, but we enable muti-thread in admin service, and we also can build muti-process easily by adding more replica of admin pods in k8s,
