### ISSUE TITLE
build web docker image fail

### ISSUE THREAD

**Issue by naili-xing** [nusdbsystem/singa-auto#85]
Step 7/10 : RUN cd web/ && yarn install --production
 ---> Running in d94df9688d03
yarn install v1.21.1
[1/4] Resolving packages...
warning @testing-library/react > @types/testing-library__react > @types/testing-library__dom@7.5.0: This is a stub types definition. testing-library__dom provides its own type definitions, so you do not need this installed.
warning react-scripts > webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning react-scripts > jest-environment-jsdom-fourteen > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning react-scripts > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
[2/4] Fetching packages...
warning sha.js@2.4.11: Invalid bin entry for "sha.js" (in "sha.js").
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
error browserslist@4.12.1: The engine "node" is incompatible with this module. Expected version "^6 || ^7 || ^8 || ^9 || ^10 || ^11 || ^12 || >=13.7". Got "13.5.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c cd web/ && yarn install --production' returned a non-zero code: 1

**Comment by chrishkchris** [comment]
hello, did you remember when was the last time it success?

**Comment by chrishkchris** [comment]
![image](https://user-images.githubusercontent.com/38325429/85736758-58d73200-b731-11ea-9c85-76b4290dbba7.png)
see if it is caused by this

**Comment by chrishkchris** [comment]
@arielclj Do you have any idea why `fsevents@2.1.2: The platform "linux" is incompatible with this module.` Last time did you success using fsevents@2.1.2 ?

**Comment by chrishkchris** [comment]
@naili-xing on the other hand, you may consider to try update the web_admin dockerfile node version
https://github.com/nusdbsystem/singa-auto/blob/dev/dockerfiles/web_admin.Dockerfile#L20 to 
`FROM node:13.5.0-alpine3.11`  to  `FROM node:14.4.0-alpine3.11`

**Comment by chrishkchris** [comment]
@naili-xing Please help to check if this PR is a good solution, thanks  https://github.com/nusdbsystem/singa-auto/pull/86
